AR_Django/AR_Django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('AR_server.urls')),
]

Tienda/urls.py
from django.conf.urls import url, include
from django.contrib import admin
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.Productos.urls')),
]

apps/Productos/urls.py
from django.conf.urls import url
from .views import *

app_name='productos'
urlpatterns = [
    url(r'^$', compras_view, name="compras_view"),
    url(r'^productos$', index_view, name="index_view"),
    url(r'^categorias$', Categorias.as_view(), name="categorias"),
    url(r'^nuevoProducto$', nuevo_producto, name="nuevo_producto"),
    url(r'^editarProducto/(?P<idProducto>.*)$', editar_producto, name="editar_producto"),
    url(r'^eliminarProducto/(?P<idProducto>.*)$', eliminar_producto, name="eliminar_producto"),
    url(r'^nuevaCategoria$', nueva_categoria, name="nueva_categoria"),
    url(r'^editarCategoria/(?P<idCategoria>.*)$', editar_categoria, name="editar_categoria"),
    url(r'^eliminarCategoria/(?P<idCategoria>.*)$', eliminar_categoria, name="eliminar_categoria"),
    url(r'^compras$', compras_view, name="compras_view"),
    url(r'^realizar_compra$', realizar_compra, name="realizar_compra"),
]

templates/categoriaFormulario.html
{% block content %}
{% include 'navbar.html' %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <h1>Categoria</h1>
      <form class="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success" name="button">Enviar</button>
      </form>
    </div>
  </div>
</div>


{% endblock %}

templates/categorias.html
{% load staticfiles %}
<!DOCTYPE html>

{% block content %}
{% include 'navbar.html' %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre Categoria</th>
      <th scope="col">Fecha Creacion</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>

  {{ data }}

  {% for datos in object_list %}
    <tr>
    <th scope="row">{{datos.id}}</th>
    <td>{{datos.nombre_categoria}}</td>
    <td>{{datos.fecha_creacion}}</td>
    <td>
      <a href="{% url 'productos:editar_categoria' datos.id %} "><button type="button" class="btn btn-info" name="button">Editar</button></a>
      <a href="{% url 'productos:eliminar_categoria' datos.id %} "><button type="button" class="btn btn-danger" name="button">Borrar</button></a>
    </td>
    </tr>
  {% empty %}
  <tr>
  <th scope="row">No hay Categorias</th>
  </tr>
  {% endfor %}
  </tbody>
</table>


{% endblock %}
  <a href="{% url 'productos:nueva_categoria'%} "><button type="button" class="btn btn-primary" name="button">Nueva categoria</button></a>

templates/compras.html
{% load staticfiles %}
<!DOCTYPE html>

{% block content %}
{% include 'navbar.html' %}
{% for datos in diccionario %}
<div class="cont_principal">
  <div class="descripcion">{{datos.1}}</div>

  <div class="img"><i class="fas fa-image"></i></div>
  <!-- <div class="precio-categoria">
    <div class="cont_pc">{{datos.0}}</div>
    <div class="cont_pc">Hay {{datos.3}} Productos</div>
  </div> -->
  <div class="nombre">{{datos.0}}</div>
  <div class="precio-categoria">
    <div class="cont_pc">${{datos.2}}</div>
    <div class="cont_pc">{{datos.4}}</div>
  </div>
  <div class="carrito">
    <input  id="cantidad_{{datos.5}}" type="number" min="0" max="{{datos.3}}" value="0">
    <i onclick="agregar_carrito('{{datos.5}}','{{datos.2}}','{{datos.0}}')" class="fas fa-cart-plus"></i>
    <p onclick="agregar_carrito('{{datos.5}}','{{datos.2}}','{{datos.0}}')" >Agregar carrito</p>
  </div>
</div>

{% empty %}
  <p>No hay Categorias</p>
{% endfor %}



<div id="resumenCarrito" class="mostrar_carrito">
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Cantidad</th>
        <th scope="col">Precio</th>
      </tr>
    </thead>
    <tbody id="cuerpo_tabla">

    </tbody>
  </table>
  <p id="total">Total: $0</p>
  <div class="precio-categoria">
    <div onclick="inicializar_datos()" style="color:white" class="cont_pc btn btn-danger">Vaciar</div>
    <div onclick="comprar()" style="color:white" class="cont_pc btn btn-info">Comprar</div>
  </div>
</div>

{% endblock %}

templates/index.html
{% load staticfiles %}
<!DOCTYPE html>

{% block content %}
{% include 'navbar.html' %}
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">ID</th>
      <th scope="col">Nombre Producto</th>
      <th scope="col">Descripcion</th>
      <th scope="col">Costo</th>
      <th scope="col">Numero de existencias</th>
      <th>Acciones</th>
    </tr>
  </thead>
  <tbody>



  {% for datos in diccionario %}
    <tr>
    <th scope="row">{{datos.id}}</th>
    <td>{{datos.nombre_producto}}</td>
    <td>{{datos.descripcion}}</td>
    <td>{{datos.costo}}</td>
    <td>{{datos.numero_existencias}}</td>
    <td>
      <a href="{% url 'productos:editar_producto' datos.id %} "><button type="button" class="btn btn-info" name="button">Editar</button></a>
      <a href="{% url 'productos:eliminar_producto' datos.id %} "><button type="button" class="btn btn-danger" name="button">Borrar</button></a>
    </td>
    </tr>
  {% empty %}
    <p>No hay Categorias</p>
  {% endfor %}
  </tbody>
</table>


{% endblock %}
  <a href="{% url 'productos:nuevo_producto'%} "><button type="button"class="btn btn-primary" name="button">Nuevo producto</button></a>

templates/navbar.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Tienda :v</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/estilos.css' %}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/funciones.js' %}"></script>
  </head>
  <body onload="inicializar_datos()">
    {% block content %}

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="{% url 'productos:compras_view'%}">Tienda :v</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'productos:compras_view'%}">Compras <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'productos:index_view'%}">Productos <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'productos:categorias'%}">Categorias </a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0" onsubmit="return false">
      <button onclick="desplegarCarrito()" class="btn btn-outline-success my-2 my-sm-0" type="submit"><i class="fas fa-shopping-cart"></i></button>
    </form>
  </div>
</nav>


{% endblock %}

  </body>
</html>

templates/productoFormulario.html
{% block content %}
{% include 'navbar.html' %}
<div class="container">
  <div class="row justify-content-md-center">
    <div class="col-8">
      <h2>Producto</h2>
      <form class="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-success btn-lg" name="button">Enviar</button>
      </form>
    </div>
  </div>
</div>


{% endblock %}